name: CI devops 2025
on:
  # Lancer ce workflow sur les branches main et develop
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  test-backend: 
    runs-on: ubuntu-22.04
    steps:
      # Checkout du code source
      - uses: actions/checkout@v2.5.0

      # Installation de JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '21'

      # Build et test du projet avec Maven
      - name: Build and test with Maven
        run: |
          cd TP1\backend-api\simple-api-student-main
          mvn clean verify
